### ISSUE TITLE
Send Usdc from sollet.io to metamask infinit error transaction

### ISSUE THREAD

**Issue by DGRZ78** [project-serum/spl-token-wallet#103]
![Sollet io](https://user-images.githubusercontent.com/79488342/108823520-d2753780-75c0-11eb-8f1f-11c5b0bcd8ed.PNG)
![After refresh on solle io](https://user-images.githubusercontent.com/79488342/108823529-d6a15500-75c0-11eb-8f64-7b9135a894e1.PNG)

I send usdc with ERC20 from sollet.io to metamask and I have a message on the fees gas to accept on metamask but he said ALERT: Insufficient funds and if I reject this, sollet.io rerun the transaction to infinity and i cant do anything. Please help me ty.

**Comment by umbit** [comment]
Same issue, any update on this? I rejected the tx on Metamask by mistake and the sollet tx is finalized and successful. I do not know how to access my USDC

**Comment by armaniferrante** [comment]
In short, you need to complete the transfer by withdrawing the funds on the ethereum blockchain, so you need to accept the metamask prompt.

Close the issue, but please join the discord for support. Lots of people there to help.

**Comment by miguel-arrf** [comment]
Hi! 

Just to clarify, if I want to reject the transaction, to not pay the fee, and have the USCD back, I can't?

Thanks.
