### ISSUE TITLE
SEED PHRASE DOES NOT allow the NEXT option for wallet restore on sollet.io

### ISSUE THREAD

**Issue by sco2021** [project-serum/spl-token-wallet#113]
I am attempting to restore my wallet on sollet.io
there is no option to sign into my wallet with my password and the 24 word seed phrase is not allowing me to choose the NEXT button to move to the next step of restoring my wallet.

**Comment by armaniferrante** [comment]
The `next` button works for me. The button will be disabled if you enter an invalid seed phrase, so my guess is that you have entered the wrong mnemonic or have a spelling error.

**Comment by sco2021** [comment]
I don't know I wrote every word down in the exact order I first saw them when I created my wallet.  I've never had issues with my seed phrases before so this is new for me.  Might it have something to do with my chrome settings to delete all my cookies every time I close the browser?

**Comment by sco2021** [comment]
@armaniferrante  IDK it's not working.  I have mulitple seed phrases ledgered down on paper and I know what all of them are for.  I wrote this one down verbatim too and double checked the word order and spelling before checking the box that I saved it.  I guess it's good I didn't have that many tokens in there!!!  Really confusing why this phrase won't work I really don't get it.  Now I have a password that doesn't mean anything and this seed phrase that I wrote down for nothing.  Also if the value of the coins continues to go up that really sucks too!

**Comment by sco2021** [comment]
@armaniferrante what would be the resolution for this?  If I have record of sending SOL from a centralized exchange to my sollet wallet and I have the wallet address shouldn't I be able to retrieve my SOL at the very least?

**Comment by armaniferrante** [comment]
> @armaniferrante what would be the resolution for this? If I have record of sending SOL from a centralized exchange to my sollet wallet and I have the wallet address shouldn't I be able to retrieve my SOL at the very least?

The challenge here is that once you move funds off a centralized exchange into a wallet you own, you take on full custody of those funds. Only people with the keys to your wallet can retrieve those funds. 

I would double check your mnemonic is correct and try again. I'm closing this issue. Since github is for development purposes. For more help, please join our discord.
