### ISSUE TITLE
Can't restore wallet from seed

### ISSUE THREAD

**Issue by camzilla1050** [project-serum/spl-token-wallet#123]
I dont know what's happening but can't restore wallet from seed.. AND neither creating a new account and adding no accept import  key..(i own only key exported in a format 84 chars)

**Comment by armaniferrante** [comment]
Is it in base58 format? If so, try decoding it into an array and pasting it into sollet 

```
new Uint8Array(require('bs58').decode('<your-key-here>'))
```

**Comment by armaniferrante** [comment]
Should be addressed by https://github.com/project-serum/spl-token-wallet/commit/bda5c4c32327ee0583faf4633a9d8e6f3f37133d. Please reopen if you have any more trouble.
