### ISSUE TITLE
Can't recover from seed

### ISSUE THREAD

**Issue by camzilla1050** [project-serum/spl-token-wallet#124]
Solved guys
Tnx

**Comment by ahmetdgd** [comment]
> guys

How did you solve that ? I cannot restore my funded account like you.

**Comment by camzilla1050** [comment]
@ahmetdgd  Hi, sollet.io changed system of import key (menu add account). I remeber the format of key doesn't match no more in the input field. I was a little disturbed by this because I have recover some times using this way when my browser crashed. And the only way to recover the wallet was from the seed. In fact, I was introducing a seed from another wallet containing no funds..I panic. Fortunately, i found the seed of the main wallet..

**Comment by armaniferrante** [comment]
As mentioned in https://github.com/project-serum/spl-token-wallet/issues/201. This is not a sollet bug. Closing.
