### ISSUE TITLE
Can't log in to my sol wallet 

### ISSUE THREAD

**Issue by ichigonani** [project-serum/spl-token-wallet#128]
Used 24 seed word and password and cannot even click next to unlock wallet. What can I do??

**Comment by armaniferrante** [comment]
You likely have a typo in your seed phrase.

**Comment by ichigonani** [comment]
No I definitely did not. But I can now log in on desktop. I tried different times on mobile checked word for word. It seems to be an issue with mobile. You should at least be able to click next to TRY to unlock even if words are not correct yes? Anyway thanks for the help.

**Comment by armaniferrante** [comment]
The next button is disabled for two reasons:

1. Either the passwords given don't match
2. The mnemonic is invalid

See https://github.com/project-serum/spl-token-wallet/blob/d6046cec0f08d9f97a1f7e9dadbdb7e1b1d4bfc3/src/pages/LoginPage.js#L258
