### ISSUE TITLE
Ledger Nano S derivation path selection

### ISSUE THREAD

**Issue by sirsatsalot** [project-serum/spl-token-wallet#133]
I created a Bonafida and Sollet wallet. 
Imported the hardware device, added funds to that address and started farming on Raydium
My webpage cache was deleted
Now when I import the hardware wallet it is a different address.
How do I change it?

**Comment by armaniferrante** [comment]
Derivation path selection introduced in https://github.com/project-serum/spl-token-wallet/pull/158.
