### ISSUE TITLE
Transaction Error - can't send SOL

### ISSUE THREAD

**Issue by josephd8** [project-serum/spl-token-wallet#14]
Every time I try to send SOL from sollet.io I get the following error:

failed to send transaction: Transaction simulation failed: TransactionError::InstructionError(0, Custom(1))

This may not be a permanent issue for anyone else - I am not sure. I just don't know where else I can get some help. Can't have SOL in a wallet that won't let me get it out.

**Comment by josephd8** [comment]
@nishadsingh1 any thoughts on where this error is coming from and how I can overcome?

**Comment by josephd8** [comment]
@bartosz-lipinski @garywang @philippe-ftx - I still cannot send SOL from my sollet.io wallet. Can someone please help me out here? Thanks.

**Comment by ericbourque29** [comment]
I have the same issue, trying to send from Sollet.io to Trust Wallet

**Comment by SOLCaptain** [comment]
having the same issue, cannot send SOL from sollet.io wallet

**Comment by mlopez66** [comment]
any news on this issue???

**Comment by oshosanya** [comment]
I also have this issue, any way to go about it?

**Comment by lunesco** [comment]
I have problems with settling funds, it doesn't work and it takes each time some SOL...

**Comment by tina1998612** [comment]
same problem anyone solve it?

**Comment by armaniferrante** [comment]
Please join discord for support.
