### ISSUE TITLE
Popup wallet broken

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/spl-token-wallet#147]
The changes in https://github.com/project-serum/spl-token-wallet/commit/754dd375955a27460e46ff01059c4d08252cfba0 have regressed the popup UI for connecting to the wallet. When trying to connect, the user now sees this, instead of the normal connection screen.

![Screenshot from 2021-03-16 12-33-43](https://user-images.githubusercontent.com/6990215/111383479-80767d80-8665-11eb-945c-236d34c1b375.png)

**Comment by jhl-alameda** [comment]
Fixed by https://github.com/project-serum/spl-token-wallet/commit/61b17cbe6caf82cf88accd9cd4852b50cfa98dad
