### ISSUE TITLE
Cannot connect to dex.projectserum.com with Sollet extension 

### ISSUE THREAD

**Issue by PaulBernier** [project-serum/spl-token-wallet#160]
- Sollet extension v0.1
- Chrome version 89.0.4389.90 (Official Build) (64-bit)
- OS: Ubuntu 20.04
 
Go to https://dex.projectserum.com/, click on connect top right, select "Sollet extension", and the following pop ups shows:

![image](https://user-images.githubusercontent.com/5141652/113467080-80140b80-93f5-11eb-8aa1-7f98596b2fd9.png)

**Comment by armaniferrante** [comment]
According to @jhlx this is fixed in the next version. And this issue affects windows and ubuntu users.
