### ISSUE TITLE
`sign` method does not work in the Chrome extension version

### ISSUE THREAD

**Issue by PaulBernier** [project-serum/spl-token-wallet#161]
- Sollet Chrome extension v0.2.3
- OS Ubuntu 20.04
- Chrome Version 89.0.4389.90 (Official Build) (64-bit)

Using `sol-wallet-adapter` library:
```
const wallet = new Wallet(window.sollet);
await wallet.connect();
const data = new TextEncoder().encode("My message");
await wallet.sign(data, 'utf8')
```
The `wallet.sign` results in a blank pop-up, looking at the console logs gives:
```
Error: Data must be an instance of Uint8Array
```
Which is this error: https://github.com/project-serum/spl-token-wallet/blob/699558770eff7d78c1fe3890eb4f83ee8a268309/src/pages/PopupPage.js#L237

I confirmed that what is sent in the `postMessage` method is effectivement a `Uint8Array`. I wonder if it gets somehow transformed/serialized when it is passed to the Chrome extension. The same code works well with sollet.io as used as a provider instead of the Chrome extension.

**Comment by jhlx** [comment]
Going to assign to you as discussed in Discord :P. Let me know if you want to pass it off / encounter any roadblocks!

**Comment by PaulBernier** [comment]
The following code handles the deserialization properly:
```js
  const urlParams = new URLSearchParams(window.location.hash.slice(1));
  const request = JSON.parse(urlParams.get('request'));
  
  if (request.method === 'sign') {
    const dataObj = request.params.data;
    // Deserialize `data` into a Uint8Array
    if (!dataObj) {
      throw new Error('Missing "data" params for "sign" request');
    }

    const data = new Uint8Array(Object.keys(dataObj).length);
    for (const [index, value] of Object.entries(dataObj)) {
      data[index] = value;
    }
    request.params.data = data;
  }

  return [request];
```
I can make the PR once the current issue with the extension on master is fixed.

**Comment by jhlx** [comment]
Hey, I think this should be unblocked now.

**Comment by PaulBernier** [comment]
Great, I have submitted a PR https://github.com/project-serum/spl-token-wallet/pull/177
