### ISSUE TITLE
Force user to input seed when logging out

### ISSUE THREAD

**Issue by jhlx** [project-serum/spl-token-wallet#163]

**Comment by armaniferrante** [comment]
Should there be a flow for if a user lost the seed and wants to wipe the wallet to create a new one?

**Comment by Arrowana** [comment]
I think this is not ideal, instead, user could be asked to provide the seed on wallet creation, metamask style
![image](https://user-images.githubusercontent.com/8245419/114510940-9eda9380-9c7a-11eb-91dc-4ffc29773547.png)
I am not sure what protection this provides but typing a seed seems like a bad idea.

**Comment by jhlx** [comment]
> Should there be a flow for if a user lost the seed and wants to wipe the wallet to create a new one?

I don't think it's possible to lose the seed before you've deleted the wallet since you can always click "Export Mnemonic", right? Or does this option go away at some point?

**Comment by jhlx** [comment]
@Arrowana I don't believe it is too late, since they can just click "Export Mnemonic" and copy the seed phrase, or am I missing something? haha.

**Comment by armaniferrante** [comment]
No I'm an idiot. You are correct. I like this feature.

**Comment by Arrowana** [comment]
@jhlx Ah understood, true you can export the mnemonic. So could a flow to "verify user has noted the mnemonic" be used when creating the wallet and when logging out?

**Comment by jhlx** [comment]
Yeah, thats a good idea @Arrowana.

**Comment by jhlx** [comment]
Done in 0.2.5.
