### ISSUE TITLE
Cannot add token

### ISSUE THREAD

**Issue by idkw** [project-serum/spl-token-wallet#192]
Cannot add token with the plus button from https://www.sollet.io/ there is a blank page and js errors
![image](https://user-images.githubusercontent.com/7012331/115059106-5e7f4d80-9ee6-11eb-828e-497c90a8e709.png)

**Comment by bmd08a1** [comment]
I'm having the same issue

**Comment by armaniferrante** [comment]
Should be addressed by https://github.com/project-serum/spl-token-wallet/commit/401789f3497df47154d43f72ea39d5af31e61599. 

I can no longer reproduce. If there's still an issue, please re-open.

**Comment by bmd08a1** [comment]
how do I update the extension?

**Comment by armaniferrante** [comment]
You can build it and run it in developer mode locally. Otherwise, you have to wait for the next release.

**Comment by idkw** [comment]
@armaniferrante thanks for the fix !
When is the next release of the extension scheduled ?
