### ISSUE TITLE
My fucking account is fucking lost 

### ISSUE THREAD

**Issue by ZeusDavid** [project-serum/spl-token-wallet#198]
I did not get a fucking 12 word or how many word seed, I just entered my password and now I am forever locked out of my account with 2.5 SOL on it which for me a student in eastern Europe is a lot of money. Can someone please help me because I am so fucking angry its not funny. I did not forget my password but it is simply not letting me log in saying my password incorrect....and I cannot even restore my account because as I said I received no fucking seed...Please help me

**Comment by nathanielparke** [comment]
Please take this issue to discord: https://discord.gg/t9dqQurS
