### ISSUE TITLE
COPE tokens unstaked from Raydium go to a different COPE address and can't be seen by Raydium

### ISSUE THREAD

**Issue by hardtofin** [project-serum/spl-token-wallet#199]
After merging the sollet.io account, when unstaking from the cope-usdc pool on raydium, the COPE tokens go to a different address in the sollet.io wallet.

This renders them invisible to the raydium app so therefore they cannot be swapped.  Any attempts to send the COPE tokens from the auxiliary address to the associated token address confirms as completed on the blockchain but the token never moves.

This effectively renders any unstaked COPE useless as it can not be converted.

**Comment by acgehr4** [comment]
Same issue.

**Comment by jhlx** [comment]
You can send the tokens from one account to the other.

If an app that you are using does not read both addresses, you may want to reach out to the devs of that app.
