### ISSUE TITLE
BOUNTY: Cannot connect to Sollet Wallet attached to my Radium Staking

### ISSUE THREAD

**Issue by warren-lorenz** [project-serum/spl-token-wallet#203]
Hello All,

I'm reaching out for some help regarding my Sollet Wallet. My computer updated overnight and it appears I was logged out of my sollet wallet. I have my seed and password but do not have the private key (that I know of unless there's a place in local storage I can look). Is there any way for me to restore the account with my seed and local password? All my assets are staked in Raydium and each time I connect a wallet path when connecting, I cannot find the right one for my staked assets. Please help. Will provide an $800 bounty for anyone who can help me unlock the wallet.

**Comment by armaniferrante** [comment]
Open up sollet in a new browser or in an incognito window and restore it. If you have your mnemonic, you don't need your password, since it's only used to encrypt the mnemonic in local storage. 

Closing. If you have further non-bug related issues, please join Discord.
