### ISSUE TITLE
Failed to withdraw RAY from sollet to FTX using SPL

### ISSUE THREAD

**Issue by Dr4nk0** [project-serum/spl-token-wallet#206]
Hi, everything is in the title.

The error i get is the following : failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

Wallet id : https://explorer.solana.com/address/HnZ6KYwFHxeqaPee8sakyKpCzs6ozU8QGnepwX1KJ6UE

Regards

**Comment by armaniferrante** [comment]
The problem is that you have zero SOL in your account. Add some SOL and the withdraw will work. Closing.

**Comment by Dr4nk0** [comment]
okay thanks
