### ISSUE TITLE
ETH missing from Metamask to Sol wallet

### ISSUE THREAD

**Issue by Harry-kimsoll** [project-serum/spl-token-wallet#208]
0.8 ETH converted from metamask to sol wallet. ethscan confirm completed but have not received to sol wallet

**Comment by armaniferrante** [comment]
Please join the discord server for support https://discord.gg/eexdUWg8. You can get help there.

**Comment by deaardi** [comment]
Apa yang harus saya lakukan


Pada tanggal Rab, 28 Apr 2021 01.26, Armani Ferrante <
***@***.***> menulis:
