### ISSUE TITLE
Restore Sollet Wallet

### ISSUE THREAD

**Issue by w3llsy** [project-serum/spl-token-wallet#210]
Hi , I am trying to restore my sollet wallet with the seed phrase, When attempting to restore it I can see the value of SOL I have in the wallet however when I actually go to restore it there is no SOL and the funds of Step and USDC I had are also not in there? Please advise.

**Comment by valcho** [comment]
A friend of mine is experiencing a similar issue with restoring from a seed phrase!

**Comment by armaniferrante** [comment]
Please try all derivation paths in the "restore" page. If you want to verify this is not a sollet bug, take the mnemonic used and derive keys in a different wallet with the same derivation path. The keys will be the same. If not, please re-open this issue. Please join Discord for more immediate support.

**Comment by w3llsy** [comment]
Hi , I can see the wallet listed in Derivable Accounts when i restore with the seedphrase however it won't allow me to select it , when i click next it just automatically I cannot pick the wallet with funds in. Thanks

**Comment by armaniferrante** [comment]
@w3llsy select the derivation path, then click `Add Account` in the account navigation until you get your derived address.

**Comment by w3llsy** [comment]
Great got it thanks. Not sure why I didn't try that :-)
