### ISSUE TITLE
Cant export mnemonic of more than one account/address

### ISSUE THREAD

**Issue by moshthepitt** [project-serum/spl-token-wallet#212]
If you have sollet set up with more than one wallet, the UI only lets you export the mnemonic of the first account added.

We should let you individually export mnemonics for each account/address.

**Comment by armaniferrante** [comment]
The one mnemonic is the mnemonic used to derive *all* the accounts not just the first. You can't have more than one mnemonic in sollet. Closing.

**Comment by moshthepitt** [comment]
> You can't have more than one mnemonic in sollet.

@armaniferrante  I think that it is possible if you had imported a private key that you got from somewhere else e.g. accounts created on the solana cli.  In such a case you won't be able to export one of those accounts (assuming you had two) out of sollet.  But maybe that's not a problem because we assume the user has their private key elsewhere?
