### ISSUE TITLE
Cannot recover sollet.io wallet

### ISSUE THREAD

**Issue by yangqing15** [project-serum/spl-token-wallet#214]
Used the recover button, but did not see my previous address. Seems, the system bug? I tried all 3 deviations but no my previous wallet. Anybody can help? Many thanks

**Comment by armaniferrante** [comment]
Please see the comment in this issue https://github.com/project-serum/spl-token-wallet/issues/201. This is very likely *not* a sollet bug. Please re-open if the steps in the other issue don't check out.

**Comment by Turnssy** [comment]
Hello I am having the same issues! Could I contact somebody in regards to a recovery process? I'm in the discord but can't talk in it. I've been using sollet for just under a week now!
