### ISSUE TITLE
SPL ETH ---> ERC20 Conversion Endless failure loop 3+ days

### ISSUE THREAD

**Issue by ozworld84** [project-serum/spl-token-wallet#217]
Hello, I know very little about programing but very involved in cryptocurrencies. I recently sent two transactions each from Sollet wallet SPL ETH to my ERC20 Meta Mask via Sollet's native conversion feature. However, both transfers are stuck in "Completing to transfer" for days now. When they time out after 50 blocks, once I click on ETH tab on Sollet wallet, Meta will reopen and ask to confirm contract interaction. If I accept it repeats the same fail after 50 blocks. If I rejects it will just ask again next time I click on the Sollet Wrapped ETH tab. Any ideas? Willing to pay $500 for anyone that can get these two TX returned or sent. Thank you for your time! Cheers, Adam

**Comment by armaniferrante** [comment]
Please join the discord for bridge support. Lots of help is given there.
