### ISSUE TITLE
Accidentally send SOL to my USDC address in sollet instead of my SOL address

### ISSUE THREAD

**Issue by jaymapss** [project-serum/spl-token-wallet#219]
Hi. I accidentally sent SOL to my sollet.io wallet USDC deposit address instead of my sollet.io wallet SOL deposit address. May I request assistance to recover the funds? Or simply move them to my SOL address instead? 

Transaction link:
https://explorer.solana.com/tx/LyN4AkGEvWjFS6Dix4EKJ69fV9BPYQLMRk6KdjCEUjZJvcatNmdJqcgB18X8eAjzRc71eLVeWoHrwegP1eBUvW8

**Comment by armaniferrante** [comment]
@jaymapss if you send SOL to *your* own SPL token address. You can get the SOL back by "closing' the account. This is a very dangerous thing to do. If you ever send tokens to this address again, you will incinerate them. If you do indeed choose to delete the address to recover your SOL, I recommend making a new wallet. If you really want to delete your spl token account for USDC here are instructions:

* go to sollet.io
* open the console
* type localStorage.setItem('warning-close-account', true)
* open up your usdc token in sollet
* send all the tokens to a new usdc account
* close the old account account by clicking `Delete`

**Comment by armaniferrante** [comment]
Please join discord for further assistance.
