### ISSUE TITLE
Sent USDC from Sollet to Meta but nothing happened 

### ISSUE THREAD

**Issue by johnyfirp549** [project-serum/spl-token-wallet#220]
Hi, 

I sent 2000 USDC from my sollet wallet to Metamask I never got a request to approve on Meta and the money seems to be gone now. Could someone please help!

Thanks,
Jonathan

**Comment by johnyfirp549** [comment]
https://explorer.solana.com/address/GaeEeZWZkesCuUu2xdkwSP9A8ZFCPmgNP5u1DKFe3zre

This is the tx hash

**Comment by armaniferrante** [comment]
Please join discord for assistance with this.
