### ISSUE TITLE
Need Help With Sollet - USDC Missing After Withdrawal

### ISSUE THREAD

**Issue by masemilo** [project-serum/spl-token-wallet#222]
I tried to withdraw USDC from sollet to my binance wallet without realising it isn't possible. The account was never credited even though the transaction says successful.

I've checked the destination on solana explorer and I don't recognise it. It also says that the account balance of said account is over 3.3 million in USDC and seems to keep going up (definitely not mine). The token balance also says there are high amount of hundreds of other coins too. 

https://explorer.solana.com/address/cPMwaM3fedMuvJHpXtF8v5re6UZkSZ6wo1JUYMFj33r 
This (above) is the account my USDC has ended up in.

https://explorer.solana.com/address/FBUKfg7Thx4WDM4ATehJe1xWzuGtMk1myXhRSvuSq19h/tokens
This (above) is the owner address and if you check the token balance it contains hundreds of other coins with extremely high balances.

I've never experienced anything like this. There's no chance I could've obtained an address that wasn't one of my own and it's been 2 days since the transaction was completed.

Can anyone please offer some advice on retrieving the USDC?

Thanks in advance.

**Comment by armaniferrante** [comment]
Please join the discord for assistance here. There's lots of people ready to help there. GitHub is mainly for dev related issues. Thank you https://discord.gg/DGTbkANw.
