### ISSUE TITLE
google or another programme must have closed some browsers and was left with this message ...

### ISSUE THREAD

**Issue by garbucci** [project-serum/spl-token-wallet#223]
![image](https://user-images.githubusercontent.com/83667435/117051202-2feada80-ad0e-11eb-8524-36750140899d.png)

tried to restore and to my utter panick l realised l only wrote down 23 words, lm assuming lm screwed unless l can somehow retore the browser ?

**Comment by armaniferrante** [comment]
Unfortunately, you need your full mnemonic to recover the wallet. For further assistance, please join the Discord. Closing.

**Comment by garbucci** [comment]
hold on yes l see that but what about some kind of restoring of my caches or browser chrome?

**Comment by armaniferrante** [comment]
Theoretically that could work. Though I've never tried.

**Comment by garbucci** [comment]
how do you restore them do you know

**Comment by armaniferrante** [comment]
I do not, unfortunately.
