### ISSUE TITLE
23 of 24 seed words , one missing ( not last word)

### ISSUE THREAD

**Issue by garbucci** [project-serum/spl-token-wallet#225]
I wrote 23 of the 24 seed words. I'm certain it's not the last word that's missing. Realistically do l have a chance of breaking it ?

**Comment by henriqueponce007** [comment]
mate same here did you get any luck? please let me know...

**Comment by garbucci** [comment]
Yep - https://zengo-x.github.io/mnemonic-recovery/

**Comment by henriqueponce007** [comment]
Hey mate thanks for that but can you please elaborate a bit more I not familiar with the tec. was your wallet Sollet for solana? if so : 
1- did you know what was the order of the missing word? 
2- Do I have to use the address of my account?
3- do you have any tutorial and can give some guidance?

thanks brother!!

**Comment by garbucci** [comment]
Hi mate ,

I don't know tbh , you have to run the programme , a relative of mine did it for me ;  brute forced and found the missing word and where my word that was missing was sequenced . If you like you can ask him to do it , but you would have to trust him in sending over the seed. I'd recommend figuring it out and trying to run it yourself .

Alexander Garbe


On 7 May 2021, at 17:19, henriqueponce007 ***@***.***> wrote:

﻿

Hey mate thanks for that but can you please elaborate a bit more I not familiar with the tec. was your wallet Sollet for solana? if so :
1- did you know what was the order of the missing word?
2- Do I have to use the address of my account?
3- do you have any tutorial and can give some guidance?

thanks brother!!

**Comment by henriqueponce007** [comment]
I see thanks mate but can you ask him to tell which program software he used? How to star how to do it please mate give a help I been reading found some stutff but did not manage was your Wallet Sollet from solana ?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by henriqueponce007** [comment]
I he send me some information and I manage I would make some donation mate please help me out you know how is the filling have 23 words missing one

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by armaniferrante** [comment]
Hey folks github issues are for developer tasks only. Please move this conversation into discord. Thanks for understanding. Closing.

**Comment by henriqueponce007** [comment]
> I wrote 23 of the 24 seed words. I'm certain it's not the last word that's missing. Realistically do l have a chance of breaking it ?

Mate can you contact me in:    henrique_ponce@hotmail.co.uk
