### ISSUE TITLE
Recover Existing Account Failed using Mnemonic word

### ISSUE THREAD

**Issue by cloud8little** [project-serum/spl-token-wallet#226]
Create account using the previous release version in Google Chrome extension, and then recover from it using mnemonic word failed to recover the previous account.

Neither of the three kinds of Derivable Accounts has my wallet account.

**Comment by GentlemansKiller** [comment]
@cloud8little Did you try restoring from mnemonic using the sollet.io website instead of the extension?

**Comment by cloud8little** [comment]
> @cloud8little Did you try restoring from mnemonic using the sollet.io website instead of the extension?

yes, still unable to recover.

**Comment by armaniferrante** [comment]
You are most likely using the wrong mnemonic. To prove this to yourself, import your mnemonic into another wallet like Trust, Phantom, Solflare, Solong, etc. If you get the correct address in any of those, and not sollet, please re-open.

**Comment by moondoll31** [comment]
I imported  my wallet to trust wallet using mnemonic pw and my address and it shows my bal somehow I am locked out of my own wallet in sollet and even restore wallet throws a new address

**Comment by cloud8little** [comment]
> You are most likely using the wrong mnemonic. To prove this to yourself, import your mnemonic into another wallet like Trust, Phantom, Solflare, Solong, etc. If you get the correct address in any of those, and not sollet, please re-open.

I am sure I am using the correct mnemonic, it makes non sense that you close the issue directly without providing a reasonable explaination!

**Comment by cloud8little** [comment]
> I believe my explanation was quite reasonable. As I said above, please feel free to re-open if you can provide proof this is a sollet bug, which can easily be done via the example I gave above. That is, import your mnemonic into a _new_ instance of another wallet. If you see the expected address there, then this may be a sollet bug and I encourage you to re-open.

It is very obvious that if I recover it correctly to my original address, I will withdraw my SOL asset and close the issue myself. What is reason you close this without proof that this IS NOT sollet bug?  I will not argue with you anymore regarding to this, I believe your action of closing this issue is WRONG.
