### ISSUE TITLE
Recovered secret keys are not validated

### ISSUE THREAD

**Issue by jstarry** [project-serum/spl-token-wallet#231]
#### Problem
Users can recover invalid secret keys which seem to work fine (display the correct address) but actually cannot be used to produce valid signatures

#### Proposed change
Update to `@solana/web3.js` v1.10.0 and switch the following usage of `new Account(...)` to [`Keypair.fromSecretKey`](https://solana-labs.github.io/solana-web3.js/classes/keypair.html#fromsecretkey) which will throw an error if the provided secret key is invalid.

https://github.com/project-serum/spl-token-wallet/blob/a666b172e930ba061776a0c9c0fb51398f0d3f6f/src/utils/utils.ts#L99-L112

**Comment by jstarry** [comment]
I'm happy to fix this if no one else gets to it before I'm back from vacation next Friday

**Comment by samhau2020** [comment]
any update on this one, can i restore the secret keys now?

**Comment by armaniferrante** [comment]
Addressed byhttps://github.com/project-serum/spl-token-wallet/pull/290.
