### ISSUE TITLE
i sent my serum to my Upbit address

### ISSUE THREAD

**Issue by lemon1825** [project-serum/spl-token-wallet#232]
i sent my serum to my Upbit address but i can't recieved yet

**Comment by armaniferrante** [comment]
Can you share the transaction? This is likely an upbit problem.

**Comment by lemon1825** [comment]
> Can you share the transaction? This is likely an upbit problem.

![AAF6D0FC-DC01-41FA-850F-479320280403](https://user-images.githubusercontent.com/83858588/117574665-2f40b280-b119-11eb-9109-cc3065b2d6f5.png)

**Comment by lemon1825** [comment]
it's right?

**Comment by GentlemansKiller** [comment]
@lemon1825 you might want to give a URL link to the transaction instead
