### ISSUE TITLE
i use raydium to do a trade but now cant see my usdt

### ISSUE THREAD

**Issue by Bilaalp** [project-serum/spl-token-wallet#238]
hi i have a trade on raydium but cant seem to find my usdt in my wallet. it says my balance is 0.the trade i have done is sol/usdt. 

can you help me to get my money back please

**Comment by armaniferrante** [comment]
See the #faq in the serum discord. https://discord.gg/yfYxsYxW For further assistance, please ask for help there. Github is for developer issues.
