### ISSUE TITLE
Cannot recover wallet,sollet wallet has bug issue

### ISSUE THREAD

**Issue by moondoll31** [project-serum/spl-token-wallet#239]
I am ready to give my seed pharse with address to mod just open the account and show me,since I have only small irrelevant amount of sol I have nothing to loose,try it out urself and see.i only deleted chrome history and I can't retrieve my old account back even with seed pharse being 100% correct it can't be wrong since I have screenshot of it.

**Comment by armaniferrante** [comment]
Assuming you have no substantial amount of tokens in your wallet, and you are ok with completely handing it over to another person, I'd be happy to take a look at the seed phrase. Can you please message on discord?

**Comment by borntoclimb** [comment]
Hello armaniferrante

I have also this prob
I have the seed phrase but impossible to recover my account, only derivates account!!
can you help?

**Comment by armaniferrante** [comment]
@borntoclimb please join discord for support requests to diagnose your problem.

**Comment by armaniferrante** [comment]
https://discord.gg/j9x2RGmU

**Comment by borntoclimb** [comment]
I send you a friend demand on discord

**Comment by moondoll31** [comment]
> Assuming you have no substantial amount of tokens in your wallet, and you are ok with completely handing it over to another person, I'd be happy to take a look at the seed phrase. Can you please message on discord?

Sending you friend request on discord link z accept it

**Comment by armaniferrante** [comment]
@moondoll31 what is your name on discord?

**Comment by moondoll31** [comment]
> @moondoll31 what is your name on discord?
l’amour est mort#9369 That’s my id sir

**Comment by armaniferrante** [comment]
I've verified the user's mnemonic against phantom, trust, and sollet. The key derivation is consistent in all cases. This is not a sollet bug. Closing.
