### ISSUE TITLE
Can't acces my wallet

### ISSUE THREAD

**Issue by alejomaler** [project-serum/spl-token-wallet#241]
I tried to acces my wallet today and the page says my password is incorrect. I have my seed words and it doesn't let me restore my password either. I don't know what to do cause I can't afford losing the money a got in Sollet. 
PLEASE HELP.

**Comment by armaniferrante** [comment]
If you have your seed phrase, you can restore your wallet by wiping sollet local storage, and restoring your account. Before doing this, please verify your seed phrase is correct by restoring in an incognito window first. This issue as reported is not a sollet bug, so please join the discord for further assistance. Closing.
