### ISSUE TITLE
Can't restore from solana-keygen seed phrase

### ISSUE THREAD

**Issue by lucky-808** [project-serum/spl-token-wallet#247]
I'm using solana-keygen on the command line to generate a keypair and seed phrase, example:

```
C:\>solana-keygen new --no-bip39-passphrase --no-outfile
Generating a new keypair
===========================================================================
pubkey: EkS3y9zSYwTGR8mT8SaeJf36UBuotjJMSY5bq8wd7NZs
===========================================================================
Save this seed phrase to recover your new keypair:
enlist essence novel wonder give inquiry saddle frog immune real tent couch
===========================================================================
```

When I load up that seed phrase into sollet.io, none of the resulting public keys match what is generated by solana-keygen:
![solana-restore](https://user-images.githubusercontent.com/84196079/118299178-6b279f00-b4ae-11eb-9aa1-66223abaec8c.png)

![sollet](https://user-images.githubusercontent.com/84196079/118298532-9231a100-b4ad-11eb-8915-115bf38d6434.png)

**Comment by armaniferrante** [comment]
It is my understanding the solana cli doesn't (yet) derive bip32+bip44 based keys. So this is expected. Closing.
