### ISSUE TITLE
Comment récupérer son Wallet Solanium Sollet sans le mot de passe de 24 mots

### ISSUE THREAD

**Issue by oxydem** [project-serum/spl-token-wallet#251]
Bonjour, après avoir effectué une mise à jour de mon ordinateur, je me suis connecté sur Solanium afin d'y connecté mon portefeuille Sollet, malheureusement mon compte n'est plus connecté dessus et je ne retrouve plus le mot de passe de 24 mots afin de le restaurer, pouvez vous m'aider ?

**Comment by oxydem** [comment]
Il me manque le code de semence, je ne le retrouve plus... je dispose de l'adresse de mon portefeuille ainsi que du mot de passe

**Comment by VnceB** [comment]
Sollet est assez clair sur la façon de récupérer le wallet lors de son initialisation:
"Your private keys are only stored on your current computer or device. You will need these words to restore your wallet if your browser's storage is cleared or your device is damaged or lost"

Si vous avez perdu la clé privée dans le localstorage du browser ET les 24 mots, vous avez effectivement perdu l'accès complet au portefeuille. Ce n'est pas une spécificité de Sollet mais bien une fonctionnalité de sécurité de tous les wallets non-custodial.

**Comment by armaniferrante** [comment]
@VnceB is correct. Only you can restore the wallet since only you have the seed phrase. Closing, as this is not a development related problem.
