### ISSUE TITLE
Lost my Seed Phrase

### ISSUE THREAD

**Issue by Turnssy** [project-serum/spl-token-wallet#252]
I feel like an idiot being here but I can't recover my seed phrase or it's showing the one I had with a 0 balance. Please help as I was trying to enter the MER ICO on the 20th.

**Comment by armaniferrante** [comment]
I'm sorry you lost your seed phrase. Please join the Discord to ask for non-development related help. Though if you dont have your correct seed phrase, there's unfortunately little others can do.  https://discord.gg/h6zHtzPv

**Comment by Turnssy** [comment]
I do have the seed phrase tho mate it's just showing 0 balance as if I emptied it?
