### ISSUE TITLE
forget my pass 

### ISSUE THREAD

**Issue by dounatia627** [project-serum/spl-token-wallet#254]
hello 
I forgot my solanium wallet pass what should I do ?
I cant also remember my seed phrase ?

**Comment by jayant289** [comment]
My phone is format,
I cant remember my seed phrase Sollet wallet what can be do ?

**Comment by Kubrakahraman775** [comment]
hello I can't find my solanium wallet, I opened a lot of addresses, none of them have solanium please help

**Comment by armaniferrante** [comment]
Github for development related issues. For support please join the discord. https://discord.gg/hWKmpe5a
