### ISSUE TITLE
Multiple USDC tokens with the same token address

### ISSUE THREAD

**Issue by dk8996** [project-serum/spl-token-wallet#257]
Multiple USDC tokens with the same token address.

![image](https://user-images.githubusercontent.com/2559655/118556957-2314b080-b72a-11eb-9bbc-034b6a66f14a.png)

**Comment by armaniferrante** [comment]
This is intended. A non-sollet app must have added this account for you. As you see, you have an auxiliary address. For further explanation and a way to remove the duplicate, see the #faq in discord.
