### ISSUE TITLE
Feature : Removing a coin from the wallet

### ISSUE THREAD

**Issue by Youcef-OB** [project-serum/spl-token-wallet#259]
Hello,

I just wanted to ask if there is a feature to remove a coin from the wallet ?

If there isn't one i really recommand to add it, because when we have a lot of coins we are fastly flooded and a bit lost.

Thank you very muuch for your time.

**Comment by armaniferrante** [comment]
Yes the feature exists (but be careful). To activate it, see the `#faq` in Discord https://discord.gg/HCsW2NCM
