### ISSUE TITLE
lost usdc coin please help

### ISSUE THREAD

**Issue by ibrahim1998104** [project-serum/spl-token-wallet#262]
i basically sent my usdc from my sollet wallet to my coinbase pro usd(c) wallet all of it went through but nothing came on coinbase pro when i made the transaction metamsk opened up and i confirmed. not too sure what went wrong can you help @armaniferrante

_Originally posted by @ibrahim1998104 in https://github.com/project-serum/spl-token-wallet/issues/205#issuecomment-844395325_

**Comment by armaniferrante** [comment]
Please join discord for support requests. There are lots of people there to help https://discord.gg/nchpPEWq.

Github is for developer issues only.

**Comment by armaniferrante** [comment]
Please see the `#faq` in the Discord, as well.
