### ISSUE TITLE
Mistakenly Sent SOL to STEP adress

### ISSUE THREAD

**Issue by krp07289** [project-serum/spl-token-wallet#264]
Hi, today I mistakenly sent SOL from binance to my sollet wallet's STEP adress. How can I fix this problem? Thank you for helping.

**Comment by armaniferrante** [comment]
See the `#faq` in the Discord. There are instructions for recovering the SOL. https://discord.gg/VP9carMY

**Comment by krp07289** [comment]
I checked the faq in the discord but whenever I used the code ;localStorage.setItem('warning-close-account', true) an undefined message appears on console

**Comment by armaniferrante** [comment]
This is expected.  `localStorage.setItem('warning-close-account', true)` activates the `Delete` button. You have to click it (once you have zero balances of the token you want to delete). Please reread the directions completely. If you have more questions, ask in the Discord.

**Comment by vicers9** [comment]
> This is expected. `localStorage.setItem('warning-close-account', true)` activates the `Delete` button. You have to click it (once you have zero balances of the token you want to delete). Please reread the directions completely. If you have more questions, ask in the Discord.

how to disable sir?
