### ISSUE TITLE
Feature: Download backup mnemonic file as setup requirement

### ISSUE THREAD

**Issue by skynetcapital** [project-serum/spl-token-wallet#268]
**Problem**

Users frequently clear their browser cache on accident, whom did not use the Export Private Key feature that Sollet provides. This creates a great deal of support requests.

**Proposed change**

Add a **required** step to Wallet setup/configuration when you are shown your seed phrase to download it. The setup will not complete unless the Download button has been clicked. The downloaded file will contain the seed phrase text.

The "Continue" button won't be clickable until the option box has been checked, and the Download button clicked.

**Concept**

![image](https://user-images.githubusercontent.com/67430414/119284935-bdc33280-bbf5-11eb-82cd-b74141e2e039.png)

**Comment by armaniferrante** [comment]
Addressed by https://github.com/project-serum/spl-token-wallet/pull/269.
