### ISSUE TITLE
Why is there no lock file?

### ISSUE THREAD

**Issue by npomfret** [project-serum/spl-token-wallet#281]
https://www.reddit.com/r/solana/comments/nsbzix/is_solletio_safe_question_to_the_engineers/

**Comment by armaniferrante** [comment]
There is a lock file. See https://github.com/project-serum/spl-token-wallet/blob/master/yarn.lock.

**Comment by npomfret** [comment]
Ah, yarn.  Apologies.  Is there a way to ensure the website uses this codebase?

**Comment by armaniferrante** [comment]
For the website, nothing is provided for verification other than the github pages deployment. Presumably you can verify the extension, though I'm not super familiar with the details. I'd recommend either running your own version of sollet to or using an extension based wallet like phantom (or the sollet extension).
