### ISSUE TITLE
address question

### ISSUE THREAD

**Issue by npomfret** [project-serum/spl-token-wallet#282]
I'm trying to withdraw an SPL token (KIN) to my Sollet wallet.  I've generated the address, and it says:

`Token Address: kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6`

But when I try and use this in FTX to two the withdrawal it tells me "invalid address".  How do I find the actual address of my SPL Token sub-wallet?

**Comment by armaniferrante** [comment]
Click the `Receive` button in the token list item you're trying to withdraw to, i.e.,  your `Kin` receive address. For further assistance, please ask on Discord.

**Comment by npomfret** [comment]
Ah. thank you and thank you

**Comment by npomfret** [comment]
A link to the discord in the README would be useful
