### ISSUE TITLE
Lost pharse wallet sollet 

### ISSUE THREAD

**Issue by apratamaa516** [project-serum/spl-token-wallet#299]
Hallo everyone

Today, im login normal, but in few" hours i can't login then sollet log out, i cant login and sollet need pharse,im forgot my pharse sollet, but im not forgot password, can fix this , anyone Dev/team sollet help me

**Comment by armaniferrante** [comment]
Unfortunately, there's nothing that can be done without your seed phrase. Closing since this isn't a dev issue. Please join the discord if you need further assistance.

**Comment by apratamaa516** [comment]
Are u have link discord ?

Pada tanggal Rab, 16 Jun 2021 03.37, Armani Ferrante <
***@***.***> menulis:
