### ISSUE TITLE
Can't restore wallet

### ISSUE THREAD

**Issue by calmcooley** [project-serum/spl-token-wallet#304]
I have Raydium staked but I can't get to my sollet.io wallet. I get a completely different address and the new one has no funds in it. The mnemonic is 100% correct but I am still not able to get into my wallet. This happened after i cleared my google chrome cache. Please assist or provide discord link please.

**Comment by armaniferrante** [comment]
Did you try all derivation paths? 

If you did, and you'd like to prove to yourself whether it is or is not the correct mnemonic, try restoring the wallet with phantom wallet and seeing if you get the same address. Key derivation is deterministic so if you use the same seed and derivation path in different wallets you'll get the same address. If you get an unexpected address still, you have the wrong mnemonic.

For further assistance, please join the discord https://discord.gg/HptFvWYm.

Closing as this is very unlikely to be a sollet issue. However, if you can restore your address in phantom or another wallet and cannot do so in sollet, please re-open.
