### ISSUE TITLE
Can't withdraw from metaplex, or import my SOL address to Phantom Wallet

### ISSUE THREAD

**Issue by CryptoRedneck** [project-serum/spl-token-wallet#306]
Hi all, summarizing my issue below:

- A few weeks ago I placed a bid on an NFT auction paying with SOL on: [https://metaplex.helium.com/#/](https://metaplex.helium.com/#/). My wallet setup is Sollet + Ledger Nano S

- I lost two auctions so need to return the same site to redeem my bid SOL

- When clicking redeem, the tx prompts in sollet, I click approve, but it never makes its way to my ledger. **Upon speaking with the Metaplex team, they inspected the console, and determined the issue to be with Sollet**. The team suggested I import the same SOL address into Phantom and attempt to redeem that way

- Upon trying to import the same wallet address into Phantom, my address aren't showing. **The derivable addresses (including the ones I use) in Sollet at m/44'/501'/0'/0' are not showing in Phantom import screen and don't match what is shown in sollet**. 

- Upon speaking with the Phantom team ([link](https://discord.com/channels/813904892778512424/825389107609862166/856350302973722635)) they recommend simply creating a new account, but that wont' solve my problem of redeeming my bid SOL

Any guidance here, on either front? Thank you for your time

**Comment by armaniferrante** [comment]
For the address, issue, I would expect the addresses shown by phantom and sollet to be the same. When you import to sollet and phantom, double check your derivation path is correct. 

For using sollet with metaplex, have you tried recently? Recently chrome broke web usb so sollet had to be updated to work with ledger again. It should work now. Also, double check you are connecting you hardware wallet before connecting to metaplex. I.e., click "Import hardware wallet" on the sollet popup, which shows after you click "Connect".

**Comment by CryptoRedneck** [comment]
Hi Armani, thanks so much for the quick reply!

Issue resolved -- I had last tried on Friday morning but the recent update appears to have fixed the issue! Thank you.
