### ISSUE TITLE
Basic swaps from SOL to SRM/RAY/OXY not working as swap button grays on hover

### ISSUE THREAD

**Issue by laurencefass** [project-serum/spl-token-wallet#322]
I am testing this wallet for the first time with a small deposit of SOL trying to convert to other SOL tokens. 

I have created balances for SRM, RAY and OXY and the basic swap function is not working. 

If i select swap SOL to any of SRM/RAY/OXY the Swap button is enablled but it grays and disables when i hover it as shown in the screenshot. There are no other errors shown on the screen. 
 
![image](https://user-images.githubusercontent.com/3512857/123796974-9d198700-d8dd-11eb-8b18-1ec0d5fa89d7.png)

Im happy to provide further info and testing if you require.

**Comment by armaniferrante** [comment]
Are you sure it's disabled it is expected to grey on hover but it should still work.

**Comment by armaniferrante** [comment]
Moving this issue to the appropriate repo https://github.com/project-serum/swap-ui/issues/63.

**Comment by laurencefass** [comment]
Hi just double checked it. Im Sure its disabled. IMHO graying on hover as a UX feature is a bit confusing, but definitely not doing anything and not swapping.

Specifically Im trying to swap 0.1 SOL for SRM/RAY etc just to prove it works. I only have one SOL in the wallet (more to come once ive proved its safe and swaps are working ok....). Could the account balance and swap amounts be too small? 

Thanks

Thanks

**Comment by laurencefass** [comment]
Hi do you have any more feedback common access via sollet.io so should be a reproducible issue. 

Generally is this the best channel for user-land support? Do you have a better support channel than github that is not discord. Email support would be more structured. I have been using Atomic Wallet recently and the email support is first class and certainly a good model to work for any organisation supporting a wallet.
