### ISSUE TITLE
No way to remove token symbol out of my wallet

### ISSUE THREAD

**Issue by quocnhat7** [project-serum/spl-token-wallet#330]
I team, I added some spl tokens into my wallet.
Now their token amount is 0, so I dont want to see that token in wallet any more. Because the list in my wallet is long now, it is hard for me to follow my wallet balance. So, delete some tokens (which have 0 tokens) is better.
But in Sollet, now there is no menu/button "Delete" to let user can do that.
(Searching from Internet, perhaps in the past you had that button, but now it was discarded).
So, how to delete token out of my wallet?
It is unreasonable to let user add but dont allow to delete. This should be an UX issue.

**Comment by armaniferrante** [comment]
Please see the faq in discord, which addresses this. https://discord.gg/GZU6ZFxR.
