### ISSUE TITLE
Infinite loading when connecting sollet.io wallet to local network

### ISSUE THREAD

**Issue by emdeutsch** [project-serum/spl-token-wallet#331]
I have followed the tutorial found here (https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/#is-there-really-a-need-for-a-temporary-account-for-alice-s-x-tokens) and built an Escrow program using Solana. I am now attempting to use the UI to test the program on a local network. In order to do so, I need to create a sollet.io wallet and connect it to my network. When I attempt to do this, here is what I see... 
![image](https://user-images.githubusercontent.com/57371702/124674327-1c7bfd00-de80-11eb-94ce-fd2125de6688.png)

![image](https://user-images.githubusercontent.com/57371702/124674290-0c641d80-de80-11eb-85db-2b538ce83fdb.png)

These loading symbols never go away, even if I reset the local network or make a new sollet.io account... Can anyone help me find out why this is happening?

**Comment by palmsey** [comment]
@emdeutsch I've run into the same thing, did you figure this out?

**Comment by evandeutsch-bravvlabs** [comment]
I was running sollet.io on safari not chrome haha
