### ISSUE TITLE
Using `getProgramAccounts` with base58 encoding is no longer valid

### ISSUE THREAD

**Issue by jstarry** [project-serum/spl-token-wallet#349]
#### Problem
A recent change in Solana has removed support for fetching program accounts with the default base58 encoding: https://github.com/solana-labs/solana/pull/18852 and this change breaks token fetching.

#### Proposed Change
Update the `getProgramAccounts` call for user tokens to use the `"encoding":"base64"` option

cc @armaniferrante

**Comment by armaniferrante** [comment]
Addressed by https://github.com/project-serum/spl-token-wallet/pull/352.
