### ISSUE TITLE
Cannot import hardware wallet.

### ISSUE THREAD

**Issue by shexcn** [project-serum/spl-token-wallet#357]
Tested with both Brave and Firefox and the problem exists in both places.
I am using ledger with updated software.

When navigating to sollet.io my existing web wallet is loaded successfully.

When clicking on Account -> Import Hardware Wallet  I see the popup.
From there clicking on Continue I see the expected derivable account from my hardware wallet.
I select it and then am prompted to confirm on my hardware wallet. After doing that I select done on the popup and am met with a blank white page.

The console printout shows two errors:

![image](https://user-images.githubusercontent.com/80130412/128383871-110d5a75-a7ac-41ef-8318-d3b54092345c.png)

The expected behavior would then be to see my hardware wallet account as has always been the case. I know I have successfully done this in the last 48 hours.

**Comment by GentlemansKiller** [comment]
Yep, I just started having this problem too, the past few days. I use Chromium, which always worked, up until now. I tried turning off any plugins, still didnt work

**Comment by GentlemansKiller** [comment]
@shexcn btw, i didnt know you could connect a ledger to sollet on firefox. Anything special you have to do for that?

**Comment by Nyxelio** [comment]
Same here

**Comment by armaniferrante** [comment]
Fixed by https://github.com/project-serum/spl-token-wallet/commit/a8d2d3b8cafafe7ba9fd7ab97f646ce923210f51.
