### ISSUE TITLE
Transfer from SPL to ERC20 stuck

### ISSUE THREAD

**Issue by EncryptedUser11235** [project-serum/spl-token-wallet#361]
I'm using sollet.io to transfer USDC from my solana wallet to my metamask. To test that it works I sent a small amount which succeeded fine. I then tried transferring more but it never asked my metamask to sign/pay the gas fee, it just removed the amount from the sollet wallet then closed the transfer window without any messages......there a way to recover this or is it just gone? The Solscan shows it's all succeeded and what not.

**Comment by armaniferrante** [comment]
Is this still a problem? Please join the Discord for assistance. There's lots of support there. https://discord.gg/QvkkPxkDUH
