### ISSUE TITLE
Can't find wallet after erase history or cookies

### ISSUE THREAD

**Issue by Oemie** [project-serum/spl-token-wallet#362]
Please help. After i erase cookies or history. My solana need to restore. After input the seed phrase when the first time i got it. I still couldnt find my account. Anyone can help? i left solana in the wallet. Thanks.

**Comment by laurencefass** [comment]
i also have a problem restoring wallet account from seed phrase.  was working now appears broken. see here for further details.
https://github.com/project-serum/spl-token-wallet/issues/366

**Comment by armaniferrante** [comment]
> Please help. After i erase cookies or history. My solana need to restore. After input the seed phrase when the first time i got it. I still couldnt find my account. Anyone can help? i left solana in the wallet. Thanks.

Do you see your address on the restore account list? If so, you need to click menu > add account to derive each one. If you don't see your account on the list, then you have the wrong mnemonic. Please join Discord for further help, as there are people there for assistance https://discord.gg/SqjjJcKu
