### ISSUE TITLE
Between m/44'/501'/0' and m/44'/501'/0'/0',  which one is recommended path for Ledger nano x? 

### ISSUE THREAD

**Issue by golftel** [project-serum/spl-token-wallet#365]
I'm trying to connect phantom wallet with my ledger nano x.  There're two different derive paths
between m/44'/501'/0' and m/44'/501'/0'/0'.      May I know which is the recommended one?
I'm thinking like one of them maybe more compatible with different type of wallet such as Sollet, Phantom
which even I lose my hardware wallet, I still can recovery my fund by importing seed phase into hot wallet no matter Phantom or Sollet without the issue.

**Comment by CoinToolInfo** [comment]
Trust Wallet uses the path m/44'/501'/0' ，
