### ISSUE TITLE
Ask for help about wallet recovery

### ISSUE THREAD

**Issue by chkoin** [project-serum/spl-token-wallet#369]
<img width="960" alt="截屏2021-08-16 19 37 56" src="https://user-images.githubusercontent.com/81691652/130100036-1e13a712-395c-456c-b2cc-c2d11789d0e7.png">No matter what I enter, it will prompt an error

**Comment by armaniferrante** [comment]
The error is showing because you only have a single letter, which is not a valid BIP 39 seed phrase.
