### ISSUE TITLE
Used Sollet to convert USDT to erc20 via metamask - Loss money

### ISSUE THREAD

**Issue by ELDumet** [project-serum/spl-token-wallet#370]
Hello, I used the send option with ERC20 USDT. Then the wallet asked me if i wanted to convert theses USDC to ERC20 using metamask. I said yes and sent them. Then nothing happened. I had a balance of 1821 USDT approximatively, and now, the balance is 0, and i can t find my USDT into metamask neither Pls help THX

**Comment by tokenwags** [comment]
Was this ever resolved?

**Comment by tokenwags** [comment]
Something similar is happening to me.

**Comment by armaniferrante** [comment]
@ELDumet @tokenwags can you provide details and share the transaction in Discord. You probably just need to complete the transfer. Also, see the #faq channel there. There's lots of people to help. Closing, but please re-open if you don't get help in Discord. https://discord.gg/SqjjJcKu
