### ISSUE TITLE
WSol to Binance, error. How could I do? 

### ISSUE THREAD

**Issue by Brando911** [project-serum/spl-token-wallet#377]
Hi, I'm sorry to have to report a deep bug that is present in the SOLLET. In the list of available coins, WSOL and SOL are not differentiated: both are called SOL and this can mislead those who want to transfer WSOL tokens on an exchange, for example. I lost my WSOLs because they were transferred to binance without the possibility of recovering them.

After I mistakenly deposited my WSOLs, the Binance system automatically '' parked '' my WSOLs on an external address they cannot access, I asked them by talking to support.

Can I retrieve my WSOL by manually calling the smart contracts of that address?

**Comment by Brando911** [comment]
Someone could help me?

**Comment by armaniferrante** [comment]
Binance can get those tokens back. And the wrapped SOL symbol is determined by https://github.com/solana-labs/token-list. Closing.
