### ISSUE TITLE
Sollet ETH Bridge withdrawal, never received ETH

### ISSUE THREAD

**Issue by 21e8** [project-serum/spl-token-wallet#382]
Hi. About 24h ago I tried to withdraw around 0.266 ETH from Sollet to Metamask.

Here is the transaction: https://solscan.io/tx/4DgXPa7HuyuRCvJ9MD4hLbryPuJUt5V6J1BdshpkQj5kpPZaiCpCavbvEux8n4Pu5gKpBs1sDz32MiHke4q8n8LE

Wallet: GoV8U9c4hjCjeosW1VKsDuRTfUe96sUPAC5RyUbstpUt
Destination on ETH: 0xa570b36ae99264777d3eb7a8e7fdfaa1ebd872f8

However, on the ETH side, nothing ever got there.
I have a comparable withdrawal from two weeks ago which went through fine.

Sorry to ask this here but I was not sure where else I could get help.

**Comment by armaniferrante** [comment]
Please see the faq in discord. And ask for support there. https://discord.gg/Ghd9gWNM
