### ISSUE TITLE
restrictions on exchanging sollet.io deposits

### ISSUE THREAD

**Issue by sco2021** [project-serum/spl-token-wallet#393]
About how long will it take for clearance of a deposit into my sollet wallet to be able to exchange on Serum Dex or swap the amount?  I see the deposit has been added to my wallet balance and it is able to be included in an order but when I approve the transaction to sell on Serum I am receiving an error message.  Also, if I open up the swap feature in the wallet it only shows the amount previous to receiving the deposit.

**Comment by armaniferrante** [comment]
This repo is not related to the serum dex. Closing.
