### ISSUE TITLE
cannot recover sollet from seed phrase nor private key 

### ISSUE THREAD

**Issue by sammansur82** [project-serum/spl-token-wallet#395]
Hello tehre I cannot recover my sollet form my seed phrase . i just recently used this seed phrase and I had no issues and now I have tried again and it silply does not work . I am trying to restore it so I can use on my computer . I also tried to link it to phantom wallet and it was not possible either even with the private key . so to test it and be sure there was an issue with sollet,  I created a new one and than I closed it and tried to restore this knew wallet a few minutes later and it does not work , does anyone knows what is happening, please. The error it gives me is that I need to imput a Bip 39 seed phrase

**Comment by Polosharko** [comment]
exactly the same problem since 5 days... lost all my funds...

**Comment by kt123123** [comment]
same my problem. the developer should explain with us

**Comment by armaniferrante** [comment]
Please import your seed phrase into another wallet like phantom. If you receive the same address, this is a proof that this is not a problem with the repository here. There is currently no reason to think this is a bug. Closing.
