### ISSUE TITLE
Funds lost

### ISSUE THREAD

**Issue by sahil827382** [project-serum/spl-token-wallet#400]
Hello sir/mam.
I restored my sollet wallet which was logged in my mobile into my laptop. As i restored all my funds get deducted to zero. I checked in my mobile wallet funds are deducted from it also. Is it bug something else. Please help

**Comment by IndestructibIe** [comment]
That same has happened with my wallet. After restore on another PC was all money lost. USDC and SOL. Please someone HELP!!!

**Comment by armaniferrante** [comment]
Please join the Discord for assistance https://discord.gg/Wg3FZ6jX. GitHub is for developer issues.
