### ISSUE TITLE
I need help, I lost my ETH when I converted to native ETH

### ISSUE THREAD

**Issue by zaki-li** [project-serum/spl-token-wallet#403]
I lost my ETH when I converted to native ETH; how could I do? I want to get back my ETH

https://solscan.io/account/SK1D4VsuwPUpXt9qk46hh8MZhwqCKfxgx2hQhrjWZgn

**Comment by armaniferrante** [comment]
Please join the Discord. There are lots of people there to help. https://discord.gg/Wg3FZ6jX
