### ISSUE TITLE
Lost USDC

### ISSUE THREAD

**Issue by bamblbii** [project-serum/spl-token-wallet#405]
I need help, I transferred USDC from sollet.io through the ERC20 network, to my binance wallet, through the ERC20 network, but I made confirmations in metamask through the Polygon network, then when I saw that I received a sending error, I needed to confirm the transaction again , I declined the transaction and my funds are gone, please help

**Comment by armaniferrante** [comment]
Please join the Discord. There are lots of people there that can help. Please provide the transaction details. https://discord.gg/Wg3FZ6jX
