### ISSUE TITLE
Wrapped SOL transferred to lost SOL wallet

### ISSUE THREAD

**Issue by dothanhvinh17** [project-serum/spl-token-wallet#412]
I transferred money from Sollet.io wallet Wrapped SOL (SOL) to SOL binance wallet, but the money was not received and lost somewhere.
How to get money back?
I tried to contact the Solscan admin but no response.

**Comment by armaniferrante** [comment]
Binance can get the tokens back since they control the wallet you sent it to.

**Comment by dothanhvinh17** [comment]
I checked on Binance, couldn't find it because SOL isn't like binance
