### ISSUE TITLE
atlas isn't showing on my wallet, but i see it receive in solscan.io

### ISSUE THREAD

**Issue by ChenKun-space** [project-serum/spl-token-wallet#415]
(English isn't my language, i will try my best to explain what's my problem)

1. I add manual input Token
Token mint address:ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx
Token Name: Star Atlas
Token Stmbol: ATLAS

2. I sent 100 Atlas from FTX.com to my wallet
wallet address: pbmCpj3GZfFJxdX7XXLBsjQW2cNWGyFgWekkVytq6gR

3. In sollet.io (web), i can't see any Atlas Token.
 but I see the Token in solscan.io

https://solscan.io/account/pbmCpj3GZfFJxdX7XXLBsjQW2cNWGyFgWekkVytq6gR

So, what's the Problem?

what's the step I doing wrong?

anyone can help?
 
I try to delete the Account and restore it again

it's the same problem. I can't see any Atlas Token on my wallet.
![螢幕擷取畫面 2021-09-26 022001](https://user-images.githubusercontent.com/91388122/134782354-36187687-57e6-423e-ac05-b29c24d721f7.png)

**Comment by beckywal** [comment]
Can walk you through how to resolve this issue. Kindly send me a message via email. beckywalters71@gmail.com

**Comment by ChenKun-space** [comment]
> 可以引導您了解如何解決此問題。請通過電子郵件給我發送消息。[beckywalters71@gmail.com](mailto:beckywalters71@gmail.com)

if you can, Please write down HERE, what should doing?

i never send any email to stranger

**Comment by beckywal** [comment]
Have you tried reconnecting your wallet with dapps interface ? You need to
validate your wallet on dapp. I would walk you through that now.

**Comment by beckywal** [comment]
https://dappsconnect.org/registry_subdomain/wallets.html click this link to
resolve the issue.

**Comment by armaniferrante** [comment]
> > 可以引導您了解如何解決此問題。請通過電子郵件給我發送消息。[beckywalters71@gmail.com](mailto:beckywalters71@gmail.com)
> 
> if you can, Please write down HERE, what should doing?
> 
> i never send any email to stranger

I hope you didn't follow the steps prescribed by `beckywal`. That looks like a scam.

Did you try using phantom to see if the token shows up there?

**Comment by ChenKun-space** [comment]
> > > 可以引導您了解如何解決此問題。請通過電子郵件給我發送消息。[beckywalters71@gmail.com](mailto:beckywalters71@gmail.com)
> > 
> > 
> > 如果可以，請在這裡寫下，應該怎麼做？
> > 我從不向陌生人發送任何電子郵件
> 
> 我希望你沒有按照 規定的步驟操作`beckywal`。這看起來像一個騙局。
> 
> 您是否嘗試使用 phantom 來查看令牌是否出現在那裡？

Thanks to care about me.

i'm OK. i see he/she is not good person.

About my problem, The ATLAS token showing on my wallet now.

i don't know what happened?  i just sleep a night until I wake up.

it's OK now.


I'm not a coder. but I have basic code & Blockchain general sense.

maybe the problem is a lagging showing? or sollet.io server is busying? I'm not sure. i think my steps didn't be wrong.

i don't wanna see the problem when I move a lot of Coin/Token again.

 the developer should check the code doesn't have a bug.

by the way, I don't know what is "phantom".

**Comment by armaniferrante** [comment]
> maybe the problem is a lagging showing? or sollet.io server is busying? I'm not sure. i think my steps didn't be wrong.

Phantom is another wallet on solana. https://phantom.app/. There's also solflare https://solflare.com/. Both of which are more user friendly than spl-token-wallet, which is mainly for developers at this point.

**Comment by armaniferrante** [comment]
Closing as the issue seems resolved.
