### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by 87JK** [project-serum/spl-token-wallet#427]
My sollet wallet was hacked, 10 solana transferred without authority to a secondary unknown wallet address. Staked solana was unstaked and sent to the same address. This happened in August.

**Comment by armaniferrante** [comment]
I'm sorry to hear that. There could be a number of reasons why that happened. Please join the Discord to discuss any details. Closing as there's no reason as of now to believe this is a development related issue. https://discord.gg/UKtY7vGz
