### ISSUE TITLE
please help me my account hack

### ISSUE THREAD

**Issue by suraj214786** [project-serum/spl-token-wallet#428]
sir my sollet account hack some please help me 
hacker address-- GbkMWeiUdBERiP13osqHHUCwYN4qEuU8BwYDBQAN5MRC
![Screenshot (39)](https://user-images.githubusercontent.com/82572658/136578138-e106863b-4024-49e7-8530-d8ee02b1a806.png)

my  address - 33gQLVvu4ndZdL2SMbdzMRy59HuFaHMRvpsup9W5UK2b
![Screenshot (40)](https://user-images.githubusercontent.com/82572658/136578191-596031bc-c0cc-4bad-84bb-45cf29f213a3.png)

**Comment by jacksmith79** [comment]
Same happened to me man I lost $500 from people hacking SMH.

**Comment by armaniferrante** [comment]
Please join the Discord to discuss your specific issue and help diagnose the problem. https://discord.gg/NDbRCcGPbn

There are a number of reasons unrelated to the development of this repository that can explain what happened. GitHub issues are for development issues only. The described issue here gives no reason to expect this is a bug in the software, and so the issue will be closed.
