### ISSUE TITLE
Accept array of transactions to sign

### ISSUE THREAD

**Issue by bartosz-lipinski** [project-serum/spl-token-wallet#51]
Right now if transaction is bigger that size limit, user needs to accept each transaction separately. It would be ideal to allow signTransaction to take list of transactions that user can approve with one click.

**Comment by bartosz-lipinski** [comment]
@nathanielparke what do you think about this change?

**Comment by nathanielparke** [comment]
Ah yep agreed this makes a ton of sense

**Comment by armaniferrante** [comment]
The change proposed in #60 adds an additional `signAllTransactions` method, instead of changing the existing one to avoid breaking existing clients.

**Comment by armaniferrante** [comment]
Completed by #60.
