### ISSUE TITLE
how to access private key 

### ISSUE THREAD

**Issue by yurenji** [project-serum/spl-token-wallet#53]
I am playing around with https://github.com/serum-community/pyserum 

For the order placing api (and some other functions), I need the private key to access my Account. 

For now, I don't have any clue how to obtain private key of sollet wallet. 

Any suggestion ?

**Comment by michaelhly** [comment]
https://github.com/michaelhly/solana-py/issues/47#issuecomment-735238646

**Comment by yurenji** [comment]
I used Solflare instead, it provides the option to download private key file. It will be helpful if sollet can provide the same option.

**Comment by armaniferrante** [comment]
@yurenji sollet does provide the option to export an account's private key. See the bottom right of the account card here 
![Screenshot from 2020-11-28 10-48-17](https://user-images.githubusercontent.com/6990215/100523704-67ee6000-3167-11eb-9fe8-a159a00d7542.png)

**Comment by armaniferrante** [comment]
Feel free to re-open if this doesn't provide the functionality you need.

**Comment by refal13** [comment]
I lost one word in sollet io 
Please help
