### ISSUE TITLE
Add label for private key import format

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/spl-token-wallet#55]
The private key imported must be base 58 encoded. We should add a label informing the user.

**Comment by armaniferrante** [comment]
Additionally we can auto convert from other formats, e.g. hex, base 64.

**Comment by self-coding-crab** [comment]
@armaniferrante Where should I show the label and what should it be?

**Comment by armaniferrante** [comment]
As discussed on Discord, go ahead and propose something and we can discuss it during review.

**Comment by self-coding-crab** [comment]
Ok

**Comment by armaniferrante** [comment]
No WIP PR has been opened. Removing assignment.

**Comment by armaniferrante** [comment]
Labeling this as P1, as it keeps coming up when talking to users.
