### ISSUE TITLE
Export private key in array format

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/spl-token-wallet#66]
Currently the private key is exported as a base 58 string. We should also add an option to export as an array so that users can easily use it with their ~/.config/solana/id.json (useful when developing).

**Comment by nyetwurk** [comment]
Also, I don't see any documentation on how to convert id.json to the base58 string (presumably needed for sollet.io import)

**Comment by evanpipta** [comment]
@armaniferrante I also commented this on the pull request, shouldn't there be an import feature for array format added at the same time? Or if not, then at least notify users who select "array format" that they cannot import it again with this UI unless they convert it back to base58?

**Comment by armaniferrante** [comment]
The base 58 import/export features has been replaced by array import/export to align with all Solana tooling. Thanks @moshthepitt and @evanpipta for the work and suggestions.

**Comment by fragosti** [comment]
@armaniferrante what Solana tooling are you referring to?

**Comment by jameslin101** [comment]
I'm trying to export a private key in array form out of phantom, still doesn't look like its supported? I only see base 58 @moshthepitt

**Comment by dahifi** [comment]
Yea, having a similar issue where I have 12 seed words from Solong wallet that I want to put in a keypair file. I can export the base58 privkey, but need it in array format. Still googling around to see what I can find.
