### ISSUE TITLE
Non-BIP44-standard key derivations

### ISSUE THREAD

**Issue by CriesofCarrots** [project-serum/spl-token-wallet#9]
It appears that the wallet is using the derivation path `m/501'/...` for wallet keys. https://github.com/project-serum/spl-token-wallet/blob/5f1dfb42c07909676da163056e8f9dce6dc772fa/src/utils/wallet.js#L37

But the BIP44 standard derivation path for solana keys is `m/44'/501'/...`
This will limit interoperability with other wallets that are using BIP44 derivations, like the Ledger hardware wallet.

Also, on a related node: the solana app for the Ledger hardware wallet only supports two levels of derivation beyond the coin type, instead of 3. It doesn't seem like sollet is using the "change" level (set to `0`), so moving to the following might make Ledger support more straightforward: `.derivePath(m/44'/501'/${walletIndex}'/${accountIndex}').privateKey;`

**Comment by CriesofCarrots** [comment]
Also, the `bip32` js library does not derive the same keys as the ed25519 implementations used by Ledger or Trezor-crypto from the same seed, since it has this hardcoded: https://github.com/bitcoinjs/bip32/blob/67ec14c86e890b5cf3c40683d494fa5472c13461/src/bip32.js#L292
ed25519: https://github.com/trezor/trezor-crypto/blob/915b3dbbbf58c262865647728a3463b8785fc965/bip32.c#L55

**Comment by armaniferrante** [comment]
Addressed by https://github.com/project-serum/spl-token-wallet/pull/42.
